[package]
name = "seg"
version = "0.1.0"
authors = ["Gökmen Görgen <gkmngrgn@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.14"
tera = "1.2.0"

[dev-dependencies]
cargo-tarpaulin = "0.12.4"
