name: release

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"

env:
    CARGO_INCREMENTAL: 0
    CARGO_NET_RETRY: 10
    RUSTFLAGS: -D warnings
    RUSTUP_MAX_RETRIES: 10

jobs:
    dist:
        name: dist
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true

            - name: Build release binary
              run: cargo build --verbose --release

            - name: Strip release binary (linux and macos)
              if: matrix.os != 'wındows-latest'
              run: strip "target/release/meyl"

            - name: Upload artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: dist-${{ matrix.os }}
                  path: ./dist

    publish:
        name: publish
        runs-on: ubuntu-latest
        needs: ["dist"]
        steps:
            - name: Get the release version from the tag
              run: |
                  echo "::set-env name=MEYL_VERSION::${GITHUB_REF#refs/tags/}"
                  echo "::set-env name=MEYL_BIN::target/release/meyl"
                  echo "version is: ${{ env.MEYL_VERSION }}"

            - name: Get the binary path (windows)
              if: matrix.os == 'windows-latest'
              run: echo "::set-env name=MEYL_BIN::target/release/meyl.exe"

            - name: Get the binary path (linux & macos)
              if: matrix.os != 'windows-latest'
              run: echo "::set-env name=MEYL_BIN::target/release/meyl"

            - name: Checkout repository
              uses: actions/checkout@v2

            - uses: actions/download-artifact@v1
              with:
                  name: dist-ubuntu-latest
                  path: dist

            - name: Get release download URL
              uses: actions/download-artifact@v1
              with:
                  name: dist-windows-latest
                  path: dist

            - uses: actions/download-artifact@v1
              with:
                  name: dist-macos-latest
                  path: dits

            - run: ls -all ./dist

            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ env.MEYL_VERSION }}
                  release_name: ${{ env.MEYL_VERSION }}
                  draft: false
                  prerelease: false

            - name: Upload release archive
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ${{ env.MEYL_BIN }}
                  asset_name: ${{ env.MEYL_BIN }}
                  asset_content_type: application/octet-stream
