name: release

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"

env:
    CARGO_INCREMENTAL: 0
    CARGO_NET_RETRY: 10
    RUSTFLAGS: -D warnings
    RUSTUP_MAX_RETRIES: 10

jobs:
    dist:
        name: dist
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true

            - name: Get the binary path (linux & macos)
              if: matrix.os != 'windows-latest'
              run: echo "::set-env name=MEYL_BIN::meyl"

            - name: Get the binary path (windows)
              if: matrix.os == 'windows-latest'
              run: echo "::set-env name=MEYL_BIN::meyl.exe"

            - name: Build release binary
              run: cargo build --verbose --release

            - name: Strip release binary
              if: matrix.os != 'windows-latest'
              run: strip target/release/${{ env.MEYL_BIN }}

            - name: Upload artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: dist-${{ matrix.os }}
                  path: target/release/${{ env.MEYL_BIN }}

    release:
        name: release
        runs-on: ubuntu-latest
        needs: ["dist"]
        steps:
            - name: Get the release version from the tag
              run: echo "::set-env name=MEYL_VERSION::${GITHUB_REF#refs/tags/}"

            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ env.MEYL_VERSION }}
                  release_name: ${{ env.MEYL_VERSION }}
                  draft: false
                  prerelease: false

        outputs:
            upload_url: ${{ steps.create_release.outputs.upload_url }}

    publish:
        name: publish
        runs-on: ubuntu-latest
        needs: ["dist", "release"]
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Download artifact
              uses: actions/download-artifact@v1
              with:
                  name: dist-${{ matrix.os }}
                  path: dist

            - name: Upload articats
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ needs.release.outputs.upload_url }}
                  asset_path: ./dist/${{ env.MEYL_BIN }}
                  asset_name: ${{ env.MEYL_BIN }}
                  asset_content_type: application/octet-stream
